### ISSUE TITLE
Possible Working Build

### ISSUE THREAD

**Issue by jhpaul** [cirosantilli/softcover_vagrant#1]
it's not exactly helping, but I think I have a working vagrant build that could use a tester. I couldn't get it to work in ubuntu but was able to build from the ground up with arch. So far I've successfully built an example_book and sc check show's all dependencies filled.

https://github.com/jhpaul/softcover-vagrant
![localhost 2014-3-12 0 9 38](https://f.cloud.github.com/assets/4071960/2393742/26e5b36a-a99c-11e3-8bf0-125406ac5340.png)

**Comment by cirosantilli** [comment]
@jhpaul Hey there, cool!

We should really decide on a single box and work together on it.

I'll work on whatever works best, but I think it would be better to use a Ubuntu 12.04 based box if we can get it working, as there are probably more developers who know Ubuntu than Arch (?)

I can also build the example book correctly.

How about where my box fails:
- can you build the PDF softcover_book https://github.com/softcover/softcover_book ? 
- does your `rake spec` pass?

Did you compile TRALICS by hand, or the precompiled binary worked? Are you also on `ruby -e 'puts RUBY_PLATFORM'` equals `i686-linux`? 

I like the idea of hosting the box on sourceforge. I'll do that too. I think it is a good idea to leave the setup script in the box, at least so that people can understand how the system is set up.

**Comment by jhpaul** [comment]
Agreed!

I spent a few too many hours over the weekend trying to get it running in ubuntu. I was running into compatibility issues since ubuntu often contains outdated packages.

Since arch is so barebones, I was able to be more selective about which versions were installed. I'd be happy to try ubuntu again, but probably won't have time to spend on it for a couple days.

I was unable to get it working under rvm or rbenv, but got good results with the native ruby install (2.1.1).

For the pdf build [softcover_book](https://dl.dropboxusercontent.com/u/1869761/softcover/softcover_book.pdf) builds but throws hbox errors and the text within code boxes doesn't wrap lines. 
Interestingly, [example_book](https://dl.dropboxusercontent.com/u/1869761/softcover/example_book.pdf) builds with no errors and does not have the hbox problem.

`ruby -e 'puts RUBY_PLATFORM'` puts `x86_64-linux`. The included tralics binary worked.

`rake spec` produces 26 failures in Builders::Htnl and Builders::Mobi [see here](https://dl.dropboxusercontent.com/u/1869761/softcover/spec-failures.txt)

I've also posted the [steps](https://dl.dropboxusercontent.com/u/1869761/softcover/softcover-arch.md) I've taken to get where I am.

**Comment by jhpaul** [comment]
whoops didn't mean to close it

**Comment by cirosantilli** [comment]
Nice. Comparison for now if I understand correctly:
- your box is better
  - works for softcover_book PDF (this one fails completely with a Ruby exception)
- this box is better:
  - `spec` has only 5 errors
  - instructions to set machine state are automatic via a sh script

I think this box is not giving HBOX warnings for example book, but I don't think that matters much for us: it should be a problem with the templates, not the install.

We have to see about box sizes, if Arch box is much smaller that would be a pro.

I'll make the box and see about that. Once I have the box I'll add an automatic box download like you have, that is the better option. That should be simple.

Sourceforge has amazingly fast download! Is hosting such a box OK with their TOS?

**Comment by jhpaul** [comment]
It should be ok with their TOS. It's possible that bundling kindlegen is a technical violation as that is not FOSS. I'll poke around more but this is the best resource I've found about their hosting policies:

http://sourceforge.net/blog/github-projects-downloads-are-welcome/

**Comment by jhpaul** [comment]
I'm heading to work, but I just got rake spec to run with it looks like 4 fails. I'll update you when I can log back in.

**Comment by jhpaul** [comment]
OK, finished out with 8 fails. Not bad compared to 26.
updated spec results here:
https://dl.dropboxusercontent.com/u/1869761/softcover/3-12-spec-failures.txt

Machine was maxing out ram which was causing the other fails. Have bumped it up to 1024 from 512 and things are working better (I haven't pushed the new vagrantfile to git yet).

Debugging the builder errors might be beyond my skills. I've posted the spec to the google group to see if anyone has thoughts. Do you?

Once everything is working, it _should_ be really easy to script an installer for arch.

**Comment by cirosantilli** [comment]
I don't have much experience with the code yet. If I find anything I'll post.

When I tried to run your VM I get:

```
Failed to open a session for the virtual machine softcover-vagrant.

Implementation of the USB 2.0 controller not found!

Because the USB 2.0 controller state is part of the saved VM state, the VM cannot be started. To fix this problem, either install the 'Oracle VM VirtualBox Extension Pack' or disable USB 2.0 support in the VM settings (VERR_NOT_FOUND).

Result Code: NS_ERROR_FAILURE (0x80004005)
Component: Console
Interface: IConsole {db7ab4ca-2a3f-4183-9243-c1208da92392}
```

Then I installed https://www.virtualbox.org/wiki/Download_Old_Builds_4_2 extension pack and it works, but I don't like that since it is another manual step.

Can we just turn off the USB support?

**Comment by jhpaul** [comment]
Yes. USB support should have been off already. I know I disabled it when I initially built the box. Not sure how it got turned back on but I will look into that.

**Comment by cirosantilli** [comment]
How are you running the spec? Bundler seems not installed in the machine I downloaded, and `rake` fails from a softcover clone under `/vagrant`.

I reproduce the PDF compiles fine on softcover_book in your machine. Any ideas why it fails for me? Which tralics are you using? I have just tested with the one at https://github.com/mhartl/tralics and still fails.

**Comment by jhpaul** [comment]
bundler isn't installed by default (I haven't rebuilt the box since we started working on it). Should be able to do `gem install bundler` to get that running. 

Are you getting the same "hbox" errors I was when building softcover_book? I'm suspicious that this could have been related to my ram issue.

I didn't install tralics independently so it is whichever version is included with `gem install softcover`

In your box, if you try `gem install softcover`, does it throw an error when install tralics? Or is it only when building? Can you send me the error text?

They're doing work at my house today and it looks like they just knocked my server offline. Unless it comes back up I won't be able to test anything until I get home in about 6 hours.

**Comment by cirosantilli** [comment]
I also get the `vbox` errors, but I really think it is related to the book or incompatibilities on the package, or mhart is just ignoring them.

Tralics compiles fine and executes, the exception is when building the PDF and is an encoding problem:

```
/home/vagrant/.rvm/gems/ruby-2.1.1/gems/polytexnic-0.9.2/lib/polytexnic/utils.rb:136:in `gsub!': incompatible character encodings: ISO-8859-1 and UTF-8 (Encoding::CompatibilityError)
```

Heard somewhere tralics has encoding problems, and waiting softcover team to decide what to do about the failing tralics install on Ubuntu before looking deeply into this: https://github.com/softcover/polytexnic/issues/100

No hurry =)

**Comment by cirosantilli** [comment]
I recommend you use the TeX Live ISO install instead of thepackage install, this way we can fix the versions more precisely. Explained in the my README how to install it.

**Comment by jhpaul** [comment]
IIRC I had a similar encoding issue when I was trying to get it working with ubuntu. I don't remember if I got past it, but you might try adapting this:
http://stackoverflow.com/a/5215676

As for the texlive iso, I will try that in the next build. The version in the Arch repo worked out of the box and self-satisfied dependencies. It was nice and easy.

**Comment by cirosantilli** [comment]
Are you on a 64 host? Can you run 32 bit guest like precise32 without turning on hardware virtualization on the BIOS?

If yes, shall we just use 32 bit machines?

I don't mind modifying my settings, but virtualization does come turned off by default in major systems (lenovo t430 here), and if we want people who are less familiar with those things to use the VM, they shouldn't have to hack their BIOS.

This SO answer also says that even for 64 bit hosts using a 64 bit guest may have complications: http://serverfault.com/a/64304/163884

**Comment by jhpaul** [comment]
32 bit is probably the way to go and should work on my machine. I initially built it for myself on my 64 bit machine. I'll do 32 bit for the next build.

**Comment by cirosantilli** [comment]
My box is 3.3 Gb.

When I try to upload to Sourceforge it says file too large... do you have a special account of some type?

If not, do you know the actual limit? Googling did not help, official pages I found said "no hard limit" or "around 5Gb".

**Comment by jhpaul** [comment]
From what I read the limit is unofficially 5gb. What protocol are you
using? I was successful with scp

**Comment by cirosantilli** [comment]
Ah, I was on the HTML form upload, didn't know that was possible! I'll try it out.

**Comment by jhpaul** [comment]
I think I read that HTML has a 1gb limit

**Comment by jhpaul** [comment]
I'll have a better writeup when I get home later and can work through it, but I've gotten to the bottom of the `Errno::ETXTBSY` errors and suspect that the problem is inherent to virtualbox. The issue relates to the difference between Windows and Unix file handling. Windows will not allow a file to be renamed our overwritten while it is open. Softcover is attempting to overwrite files, but is reporting "FIle Busy". 

Without having a machine to test on, hypothetically the issue would not exist on *nix or OSX hosts. **My next step is to try the new SMB shared folder protocol which was added in the most recent vagrant update (1.5.0).**

More info here:
https://www.virtualbox.org/ticket/2553
https://forums.virtualbox.org/viewtopic.php?f=3&t=44971

**Comment by cirosantilli** [comment]
I tried your machine on uname -a:

```
Linux ciro-ThinkPad-T430 3.11.0-18-generic #32~precise1-Ubuntu SMP Thu Feb 20 17:54:21 UTC 2014 i686 i686 i386 GNU/Linux
```

And the softcover_book and the template compiled fine.

The `rake spec` hangs forever at a single test around 122. Up to this point there were two failures. I do C^C, `rake spec` again, and it spits: http://pastebin.com/Vap56TxS before restarting.
No `Errno::ETXTBSY` so far.

---

I uploaded my machine via scp. Does it also take around 15 hours for your upload? If you can try it out on your 64 bit machine and see if you reproduce my README status that would be great.

**Comment by jhpaul** [comment]
Downloading your box now. 

Your results with my box are encouraging and in line with what I expected. The `Errno:ETXTBSY` issue being windows related seems confirmed. I'm working on ideas for a workaround.

Interesting on the long hang. Did you kill it after 10 minutes? Might be worth letting it run for a while to see if it gets past the hang and we can see the cause. Early in the build process I was having rspec take 15-20min. Now it's taking about 4 minutes.

Otherwise, it's just an issue with epubcheck. I'll need to figure out whether this a problem with the test or the program. I'm going to try replacing epubcheck3.0 with 3.1 to see if there is an effect there.

---

As for scp, I suspect your slow upload is ISP related. Mine took a while (maybe 3 hrs) to upload and I'm on a fiber optic line with 25Mbps upload. Less likely but possible that it could be a slowdown in your machine's ssh implementation.

**Comment by cirosantilli** [comment]
I have tried again, `vagrant destroy`, and same result after:

```
cd /vagrant
git clone https://github.com/softcover/softcover
cd softcover
gem install bundler
bundle install
bundle exec rake spec
```

Left running for 2 hours and nothing. My tests end in 5 minutes too, so there is probably a problem.

**Comment by jhpaul** [comment]
OK good to know. I'll  post my errors later when I'm home, but with your
box I had issues with the vagrantfile. After debugging I got the box to
boot. Running rspec with the softcover directory in /vagrant/projects threw
a ton of extno errors. Once I moved it to ~/ I had 5 fails.

I haven't been able to try smb yet.

**Comment by jhpaul** [comment]
Ok, here are the errors when running in the projects directory:
http://pastebin.com/rCV0GFXt

And this is when I move the directory into ~/
http://pastebin.com/5TQUtb2Q

**Comment by cirosantilli** [comment]
Thanks! What system are you on? On the home its what I expected, under `/vagrant/projects` must be linked to shared folder problems which do not happen in my system. Seems to be similar to what was happening on your box for windows.

**Comment by jhpaul** [comment]
Win7x64. Nearly positive it's shared folder related. Haven't had a chance
to debug yet

**Comment by cirosantilli** [comment]
@jhpaul I moved to a x86_64 machine Linux OS, you say you had problems with epubcheck, what exactly is the problem?

For me now, HTML and PDF build fine, `build:epub` and tests hang.

**Comment by jhpaul** [comment]
IIRC epubcheck errored out both when run by softcover and when run manually. I think this was the related rspec error:

```
  4) Softcover::Builders::Epub for a Markdown book should be valid
     Failure/Error: expect(`softcover epub:validate`).to match(/No errors or warnings/)
       expected "Validating EPUB...\nEpubcheck Version 3.0\n\n" to match /No errors or warnings/
       Diff:
       @@ -1,2 +1,3 @@
       -/No errors or warnings/
       +Validating EPUB...
       +Epubcheck Version 3.0
     # /home/vagrant/softcover/spec/builders/epub_spec.rb:192:in `block (3 levels) in <top (required)>'
```

I'll try look into it more when I get home tonight.

**Comment by cirosantilli** [comment]
Ah, the problem was an outdated PhantomJS, Ubuntu 12.04 repos have 1.4, but most recent is 1.9 and worked. Opened issue at: https://github.com/softcover/softcover/issues/101

Now I have only 3 failing tests on Ubuntu 12.04 x86_64, two of them spitting:

```
ERROR: ebooks/test-book.epub: I/O error: error in opening zip file 

Check finished with warnings or errors
```

**Comment by jhpaul** [comment]
I believe I was getting the same errors. epubcheck was failing on the test
files. I also had missing images in the pdfs that were created. Trying to
get my vm running, but don't quite remember where I left off.

**Comment by cirosantilli** [comment]
If you manage to get it running, please tell me exactly which images you are missing on the PDFs so I can see if I reproduce. My PDFs have images, but I haven't checked every single one.

BTW, I'm considering starting up a CI service for Softcover that deploys so `softcover.io` as explained in: https://github.com/softcover/softcover/issues/100, as part or my project https://github.com/cirosantilli/booktree (after the CI, next step will be to hack GitLab to optimize it for book development). If you have experience / advice on which CI / deployment method to use, I'd love to hear. Considering mostly Drone and Travis now.

**Comment by jhpaul** [comment]
Definitely the cover was missing. Will let you know.

**Comment by cirosantilli** [comment]
Found the cause of the 2 ePub fails: https://github.com/softcover/softcover/issues/102

**Comment by cirosantilli** [comment]
And patched the third! https://github.com/softcover/softcover/pull/103

**Comment by jhpaul** [comment]
Excellent! I'm super busy this week but will try to put some time into it.

**Comment by pussinboots** [comment]
Hello guys and of course girls.

i setup a running project https://github.com/pussinboots/book to publish a softcover book with Travis CI. It could be faster but for the moment it work. Install the needed texlive packages and softcover set the api key and perform softcover publish. There is a problem when it comes to latex interactive warnings maybe you know how to avoid the interactive latex console stuff.

great tool softcover.

**Comment by cirosantilli** [comment]
I am quite interested in a travis-like build for books to allow complete online book development, but to be usable packages would have to be pre installed, and users should be able easily view the outputs while editing: https://github.com/booktree/booktree

**Comment by pussinboots** [comment]
The travis ci build took to long for immediatly feedback so i implemented a little nodejs service that use softcover to build books directly fetched from github. If you are interested in take a look on the https://github.com/pussinboots/heroku-softcover project it is hosted on an amazon ec2 instance because i need a writable filesystem (not easy possible with heroku at the moment). An example usage to build the softcover book itself http://nnamretti.ddns.net/api/build/html/pussinboots/book/. The first build take only up to 2 minutes because it performs a complete git clone but after that it only performs git pull so the book can be build in less than a minute. The project was done in just 2 days.

**Comment by cirosantilli** [comment]
Thanks for the link! I wish we could reuse functionality from existing CIs (by hacking / hosting them if necessary), but a few attempts showed that it is not trivial. Maybe building from scratch works best in this case as you did.

**Comment by pussinboots** [comment]
That was also my experience during this softcover automate building stuff. In the end there is no need for a complete CI system. The nodejs support for github or special git is really good. So it was very easy to implement a service that does git clone and git pull to get the actual book base (instead of code base). Than run softcover as shell script and more or less you are down. 

They are still missing feature and robustness but it seems possible with just some lines of code and maybe use the softcover ruby library instead of the softcover command line. It is written in ruby and i'am not so familiar with ruby these days. 

Good luck for your booktree project.
